# ──────────────────────────────────────────────────────────────────────────────
# Inventory file for Ansible to manage RHEL 9 and RHEL 10 servers.
# ──────────────────────────────────────────────────────────────────────────────
[defaults]
localhost

#[rhel9]
#rhel9-host1.example.com
#rhel9-host2.example.com  ansible_user=ec2-user

#[rhel10]
#rhel10-host1.example.com

#[rhel_servers:children]
#rhel9
#rhel10

#[rhel_servers:vars]
#ansible_user=ansible
#ansible_become=true
#ansible_become_method=sudo
